Hw2
zfreiter/frontend-homework pull request #2
Opened 2023-04-24 17:18 UTC by zfreiter

01-flexbox.md - Text solutions added.
02-cssgrid.md - Text solutions added.

 03-count -
- Bootstrap added to html.
- Created a function to highlight all character's that a user enters.

04-background - 
- Bootstrap added to html.
- Created a function to generate a random color.
- Created a function that takes a positive value and uses that value to determine when the background color will change.

05-form - 
- Bootstrap added to html.
- Added an submit event listener for the form. It will display what the user inputs.

2023-04-28 01:33 UTC, Iwasson commented on hw2/04-background.js
> +  )}, ${Math.floor(Math.random() * 100)}%)`;
By default Math.random() returns a random float between 0 and 1. By default rgba uses a decimal number for opacity so you can simplify this code quite a bit by removing the percentage and flooring

2023-04-28 01:35 UTC, Iwasson commented on hw2/04-background.js
> +      /* Reloads the page to cancel the setInterval */
You should use clearInterval(colorChange) here instead of reloading the page.

2023-04-28 01:37 UTC, Iwasson commented on hw2/05-form.js
> +  /* RESET FORM VALUES */
you can simplify this down to document.getElementById("myform").reset();

2023-04-28 03:04 UTC, zfreiter commented on hw2/04-background.js
> +  )}, ${Math.floor(Math.random() * 100)}%)`;
Good catch.

2023-04-28 03:08 UTC, zfreiter commented on hw2/04-background.js
> +      /* Reloads the page to cancel the setInterval */
I used window.location.reload(true); because it was a listed resource.

2023-04-28 03:10 UTC, zfreiter commented on hw2/05-form.js
> +  /* RESET FORM VALUES */
Good suggestions.

2023-04-28 20:05 UTC, ssiddhi reviewed
Hey Zachary,
I have provided my review on this pull request.

2023-04-28 20:05 UTC, ssiddhi commented on hw2/05-form.html
> +        </div>
Your code is giving accessibility error: Broken ARIA reference. You might want to fix it by giving element referenced in the aria-describedby, a proper label. Everything else looks good. Code is responsive, works on different browsers and looks similar to the screenshot in pdf. Great job 👍

2023-04-28 20:05 UTC, ssiddhi commented on hw2/05-form.js
> +});
Code is working as expected. Nice work on this exercise 👍

2023-04-29 03:17 UTC, rutujapadgilwar requested changes
Exercise 01, 02 --> perfectly fine.
Exercise 03, 04, 05 --> I saw you made changes and now everything looks good to me. Just one background color suggestion in exercise 04.

2023-04-29 03:17 UTC, rutujapadgilwar commented on hw2/03-count.html
>        <div>
Everything looks fine, no changes.

2023-04-29 03:17 UTC, rutujapadgilwar commented on hw2/03-count.js
Working perfectly now. You did a good job by adding the required changes. Nice work with exercise 03.

2023-04-29 03:17 UTC, rutujapadgilwar commented on hw2/04-background.html
> +  <body style="background-color: #6c61db">
You did a perfect job adding the exact background color as the screenshot shows.

2023-04-29 03:17 UTC, rutujapadgilwar commented on hw2/04-background.html
> +      class="d-flex flex-column justify-content-center rounded m-auto mt-5 p-3 mr-1 bg-white"
In the screenshot, the background color is "bg-light"

2023-04-29 03:17 UTC, rutujapadgilwar commented on hw2/04-background.js
The code looks good!

2023-04-29 03:17 UTC, rutujapadgilwar commented on hw2/05-form.html
Now everything looks good to me.

2023-05-10 16:38 UTC, merged